### ISSUE TITLE
yarn server gulp start returns "UnhandledPromiseRejectionWarning: TypeError: Object.fromEntries is not a function"

### ISSUE THREAD

**Issue by Luca409** [mail-my-ballot/mail-my-ballot#11]
See code snippet below:

```
lucaloncar@vbm-dev:~/mail-my-ballot$ yarn server gulp start
yarn run v1.22.4
$ yarn workspace @vbm/server gulp start
$ gulp start
[17:53:50] Using gulpfile ~/mail-my-ballot-work/mail-my-ballot-forks/wyoming/mail-my-ballot/packages/server/gulpfile.js
[17:53:50] Starting 'start'...
Using ts-node version 8.6.2, typescript version 3.7.5
app listening on port 8080
(node:13252) UnhandledPromiseRejectionWarning: TypeError: Object.fromEntries is not a function
    at /home/lucaloncar/mail-my-ballot-work/mail-my-ballot-forks/wyoming/mail-my-ballot/packages/server/src/service/contact/loader.ts:20:22
    at Generator.next (<anonymous>)
    at fulfilled (/home/lucaloncar/mail-my-ballot-work/mail-my-ballot-forks/wyoming/mail-my-ballot/packages/server/src/service/contact/loader.ts:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:13252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by tianhuil** [comment]
I use to encounter this problem and it went away with some tinkering but without a satisfying solution.  TS is constantly evolving so we need the latest version.  According to [this](http://kangax.github.io/compat-table/es2016plus/), `Object.fromEntries` is defined in `es2019`, which should be included in `esnext`?  This is specified in `packages/server/tsconfig.json`.  Try tweaking with it and let me know what works (in theory, it should only require `esnext` or `es2019`).

**Comment by tianhuil** [comment]
Closing since it doesn't sound like there's any further issues.

**Comment by Luca409** [comment]
Hmm yeah unfortunately I couldn't get this to work on my GCP VM, but got it working locally on my Mac.  Guess that'll have to do for now.
